ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -21,7 +21,8 @@ jobs:
       contents: write # needed updating dependabot branches
 
   lint:
-    needs: [ get-values ]
+    needs:
+      - get-values
     name: Pre-commit
     uses: ./.github/workflows/pre-commit.yaml
     permissions:
@@ -31,7 +32,8 @@ jobs:
       python-version: 3.12.7
 
   test:
-    needs: [ lint ]
+    needs:
+      - lint
     strategy:
       matrix:
         os:
@@ -89,7 +91,8 @@ jobs:
           slug: LabAutomationAndScreening/cloud-courier
 
   executable:
-    needs: [ test ]
+    needs:
+      - test
     strategy:
       matrix:
         os:
@@ -124,7 +127,8 @@ jobs:
 
 
   build-docs:
-    needs: [ lint ]
+    needs:
+      - lint
     strategy:
       matrix:
         python-version:
@@ -156,17 +160,25 @@ jobs:
     permissions:
       statuses: write # needed for updating status on Dependabot PRs
     needs:
-      - test
       - get-values
+      - test
       - build-docs
       - executable
     if: always()
     timeout-minutes: 2
     steps:
       - name: fail if prior job failure
-        if: needs.test.result != 'success' || needs.build-docs.result != 'success' || needs.executable.result != 'success'
         run: |
-          exit 1
+          failure_pattern="^(failure|cancelled)$"
+
+          if [[ "${{ needs.get-values.result }}" =~ $failure_pattern ]] ||
+              [[ "${{ needs.build-docs.result }}" =~ $failure_pattern ]] ||
+              [[ "${{ needs.executable.result }}" =~ $failure_pattern ]] ||
+              [[ "${{ needs.test.result }}" =~ $failure_pattern ]]; then
+              echo "❌ One or more jobs failed or were cancelled"
+            exit 1
+          fi
+          echo "✅ All jobs completed successfully or were skipped"
       - name: Mark updated Dependabot commit of devcontainer hash as succeeded
         if: needs.get-values.outputs.dependabot-commit-created == 'true'
         env:
